---
docker_apt_arch:        "{{ 'arm64' if ansible_architecture in ['aarch64','arm64'] else 'amd64' }}"
docker_apt_release:     "{{ ansible_distribution_release | lower }}"
docker_apt_repo_url:    "https://download.docker.com/linux/ubuntu"
docker_apt_keyring:     "/etc/apt/keyrings/docker.gpg"
docker_apt_repo_list:   "/etc/apt/sources.list.d/docker.list"

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_users:
  - "{{ ssms_app_user }}"
