global:
  scrape_interval: 5s
  scrape_timeout: 4s
  evaluation_interval: 15s

scrape_configs:
  - job_name: ssms_backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend:8000
        labels:
          service: ssms-backend
          env: docker

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
