---
common_base_packages:
  - ca-certificates
  - curl
  - git
  - gnupg
  - lsb-release
  - ufw
  - htop
  - jq
  - python3
  - python3-pip
  - unzip

common_timezone: "Etc/UTC"
common_enable_ufw: true
